# adminpanel/urls.py
from django.urls import path
from .views import (
    AdminLoginView,
    ConsultationsListAPIView,
    AnalyzeListAPIView,
    RegisteredUsersListAPIView,
    RegisteredUserDeleteAPIView,
    ConsultationRequestDeleteAPIView,
    AnalysisHistoryListView,
    AnalysisHistoryDetail,
    AdminProductListCreateView,
    AdminProductRetrieveUpdateDestroyView,
    AdminOrderListView,
    ConfirmOrderView,
    AdminOrderDeleteView,
    ContactMessageListView,
    AdminReplyEmailView,
    update_order_status,
    ContactMessageDeleteView,
    CarouselImageAdminView,
    CarouselImageDetailView,
    FAQListCreateView,
    FAQDeleteView,
)
from django.contrib.auth import views as auth_views
from . import views
urlpatterns = [
    path('users/', RegisteredUsersListAPIView.as_view(), name='users-list'),
    path('users/<str:email>/delete/', RegisteredUserDeleteAPIView.as_view(), name='user-delete'),
    path('login/', AdminLoginView.as_view(), name='admin-login'),
    path('consultations/',ConsultationsListAPIView.as_view(), name='consultations-list'),
    path('analyze/list/',AnalyzeListAPIView.as_view(), name='analyze-list'),
    path('consultations/<int:id>/delete/', ConsultationRequestDeleteAPIView.as_view(), name='consultation-delete'),
    path('api/admin/analyze/list/', AnalysisHistoryListView.as_view(), name='admin-analyze-list'),
    path('api/analyze/<int:pk>/', AnalysisHistoryDetail.as_view(), name='analysis-detail'),
    path('products/', AdminProductListCreateView.as_view(), name='admin-product-list'),
    path('products/<int:pk>/', AdminProductRetrieveUpdateDestroyView.as_view(), name='admin-product-detail'),
    path('orders/', AdminOrderListView.as_view(), name='admin-order-list'),
    path('orders/<int:pk>/confirm/', ConfirmOrderView.as_view(), name='confirm-order'),
    path('orders/<int:pk>/delete/', AdminOrderDeleteView.as_view(), name='admin-order-delete'),
    path('contact-messages/', ContactMessageListView.as_view(), name='admin-contact-messages'),
    path('send-reply/', AdminReplyEmailView.as_view(), name='admin-send-reply'),
    path('orders/<int:pk>/update/', update_order_status, name='update-order-status'),
    path('contact-messages/<int:id>/delete/', ContactMessageDeleteView.as_view()),
    path('password-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('carousel/manage/', CarouselImageAdminView.as_view(), name='carousel-admin'),
    path('carousel/manage/<int:pk>/', CarouselImageDetailView.as_view(), name='carousel-detail'),
    path('faqs/', FAQListCreateView.as_view(), name='faq-list-create'),
    path('faqs/<int:pk>/', FAQDeleteView.as_view(), name='faq-delete'),
    path('blogs/', views.blog_list_create),
    path('blogs/delete/<int:id>/', views.delete_blog),
    path('all-ratings/', views.all_ratings),
    path('toggle-rating/<int:pk>/', views.toggle_rating),
    path('delete-rating/<int:pk>/', views.delete_rating),
    path('consultations/<int:id>/update/', views.update_consultation),

]
