from django.urls import path

from . import views
from .views import (
    AddToCartView,
    AnalysisHistoryCreate,
    AnalysisHistoryDetail,
    AnalysisHistoryListView,
    CarouselImageListView,
    CartItemDetail,
    CartItemListView,
    ConsultationRequestCreate,
    ContactMessageCreateView,
    FAQListPublicView,
    LatestAnalysisHistoryView,
    OrderListView,
    OrderRetrieveUpdateDestroyView,
    PlaceOrderView,
    ProductListView,
    ProfileUpdateView,
    UserLoginView,
    UserRegistrationView,
    approved_ratings,
    change_password,
    create_checkout_session,
    forgot_password,
    get_prediction_mapping,
    get_profile_image,
    google_login,
    health_check,
    submit_rating,
    upload_profile_image,
)

urlpatterns = [
    path("user/analysis-summary/<str:email>/", views.analysis_summary),
    path("user/recommended-products/<str:email>/", views.recommended_products),
    path("blogs/", views.blogs),
    path("user/activity/<str:email>/", views.user_activity),
]


urlpatterns = [
    path("health/", health_check, name="health-check"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("login/", UserLoginView.as_view(), name="login"),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("cart/add/", AddToCartView.as_view(), name="add-to-cart"),
    path("cart/", CartItemListView.as_view(), name="cart-list"),
    path("cart/<int:pk>/", CartItemDetail.as_view(), name="cart-detail"),
    path("orders/place/", PlaceOrderView.as_view(), name="place-order"),
    path("orders/", OrderListView.as_view(), name="order-list"),
    path("analyze/", AnalysisHistoryCreate.as_view(), name="analyze"),
    path(
        "analyze/latest/", LatestAnalysisHistoryView.as_view(), name="latest-analysis"
    ),
    path("analyze/list/", AnalysisHistoryListView.as_view(), name="list-analysis"),
    path("analyze/<int:pk>/", AnalysisHistoryDetail.as_view(), name="analysis-detail"),
    path(
        "consultations/",
        ConsultationRequestCreate.as_view(),
        name="consultation-create",
    ),
    path("profile/update/", ProfileUpdateView.as_view(), name="profile-update"),
    path("change-password/", change_password, name="change_password"),
    path(
        "orders/<int:pk>/",
        OrderRetrieveUpdateDestroyView.as_view(),
        name="order-detail",
    ),
    path("contact/", ContactMessageCreateView.as_view(), name="contact-message"),
    path("upload-profile-image/", upload_profile_image, name="upload-profile-image"),
    path("get-profile-image/", get_profile_image, name="get-profile-image"),
    path("forgot-password/", forgot_password, name="forgot-password"),
    path(
        "create-checkout-session/",
        create_checkout_session,
        name="create-checkout-session",
    ),
    path("carousel/", CarouselImageListView.as_view(), name="carousel-public"),
    path("faqs/", FAQListPublicView.as_view(), name="faq-public"),
    path("user/analysis-summary/<str:email>/", views.analysis_summary),
    path("user/recommended-products/<str:email>/", views.recommended_products),
    path("blogs/", views.blogs),
    path("user/activity/<str:email>/", views.user_activity),
    path("rate-service/", submit_rating),
    path("approved-ratings/", approved_ratings),
    path("prediction-mapping/", get_prediction_mapping, name="prediction-mapping"),
    path("google-login/", google_login),
    path(
        "user/consultations/<str:email>/",
        views.user_consultations,
        name="user-consultations",
    ),
    path("consultation-payment/", views.create_consultation_checkout_session),
]
