# Generated by Django 5.1.1 on 2025-05-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0004_blogpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='predicted_condition',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
