# Generated by Django 5.1.1 on 2025-05-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0005_analysishistory_predicted_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysishistory',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
