# Generated by Django 5.1.1 on 2025-05-04 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0007_servicerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerating',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='profile_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='servicerating',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
