# Generated by Django 5.1.1 on 2025-05-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aurora', '0008_servicerating_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationrequest',
            name='assigned_consultant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='confirmed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='confirmed_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='meeting_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='meeting_type',
            field=models.CharField(choices=[('online', 'Online'), ('physical', 'Physical')], default='physical', max_length=20),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
